// Generated by CoffeeScript 1.7.1
$(function() {
  $.fn.isVisible = function() {
    return $.expr.filters.visible(this[0]);
  };
  return $.fn.createSheet = function() {
    var x, y;
    x = $(this).find("[name=x]").val();
    y = $(this).find("[name=y]").val();
    console.log("X = " + x + ", Y = " + y);
    return false;
  };
});
