// Generated by CoffeeScript 1.7.1
$(function() {
  var blink, showSizeError;
  $.fn.isVisible = function() {
    return $.expr.filters.visible(this[0]);
  };
  blink = function(elm, speed, count) {
    if (speed == null) {
      speed = "fast";
    }
    if (count == null) {
      count = 2;
    }
    if (elm.isVisible()) {
      if (count === 0) {

      } else {
        elm.fadeOut(speed, function() {
          return $(this).fadeIn(speed);
        });
        return blink(elm, speed, count - 1);
      }
    }
  };
  showSizeError = function(elm) {
    if (elm.isVisible()) {
      return blink(elm);
    } else {
      return elm.show("fast");
    }
  };
  return $("#size").submit(function() {
    var msg, x, y;
    x = Number($("#size [name=x]").val());
    y = Number($("#size [name=y]").val());
    msg = $("#size_error");
    if (isNaN(x) || isNaN(y) || x <= 0 || y <= 0) {
      showSizeError(msg);
    } else {
      alert($.type(x) + ("" + x));
    }
    return false;
  });
});
