// Generated by CoffeeScript 1.7.1
$(function() {
  return $("#size").validate({
    rules: {
      x: {
        required: true,
        digits: true,
        min: 1
      },
      y: {
        required: true,
        digits: true,
        min: 1
      }
    },
    submitHandler: function(form) {
      return $(form).createSheet();
    },
    errorClass: "has-error",
    validClass: "has-success",
    errorPlacement: function(error, element) {},
    highlight: function(element, errorClass) {
      var message;
      message = $("#size_error");
      $(element).parent().addClass(errorClass);
      if (message.isVisible()) {
        return message.find("p[name=message]").fadeOut("fast", function() {
          return $(this).fadeIn("fast");
        });
      } else {
        return message.show("fast");
      }
    },
    unhighlight: function(element, errorClass) {
      $("#size_error").hide("fast");
      return $(element).parent().removeClass(errorClass).addClass("has-success");
    }
  });
});
