// Generated by CoffeeScript 1.7.1
$(function() {
  $("#size").validate({
    rules: {
      x: {
        required: true,
        digits: true,
        min: 1
      },
      y: {
        required: true,
        digits: true,
        min: 1
      }
    },
    submitHandler: function(form) {
      $("#size_error").hide("fast");
      return $(form).createSheet();
    },
    invalidHandler: function(form, validator) {
      return $("#size_error").showError();
    },
    errorClass: "has-error",
    validClass: "has-success",
    errorPlacement: function(error, element) {},
    highlight: function(element, errorClass) {
      return $(element).parent().addClass(errorClass);
    },
    unhighlight: function(element, errorClass) {
      return $(element).parent().removeClass(errorClass).addClass("has-success");
    }
  });
  $("#answerForm").validate({
    rules: {
      length: {
        required: true,
        digits: true,
        min: 1
      }
    },
    submitHandler: function(form) {
      $("#answer_error").hide("fast");
      return $(form).createAnswer();
    },
    invalidHandler: function(form, validator) {
      return $("#answer_error").showError();
    },
    errorClass: "has-error",
    validClass: "has-success",
    errorPlacement: function(error, element) {},
    highlight: function(element, errorClass) {
      return $(element).parent().addClass(errorClass);
    },
    unhighlight: function(element, errorClass) {
      return $(element).parent().removeClass(errorClass).addClass("has-success");
    }
  });
  $.fn.createAnswer = function() {
    var answer, i, input, len, td, tr, _i;
    answer = $("#answer");
    if (answer.find("input").length > 0) {
      $("#answerAlreadyExistsError").showError();
    } else {
      $("#answerInvisibleError").hide("slow");
      tr = answer.find("tr");
      len = $(this).find("input[name=length]").val();
      for (i = _i = 1; _i <= len; i = _i += 1) {
        input = $("<input type='text' autocomplete='off' class='text-center'>");
        td = $("<td class='text-center'>");
        td.append(input);
        tr.prepend(td);
      }
      answer.animate({
        height: "toggle",
        opacity: "toggle"
      }, "slow", function() {
        answer.find("input")[0].focus();
        return answer.registerKeys();
      });
    }
    return false;
  };
  $.fn.showError = function() {
    if ($(this).isVisible()) {
      return $(this).find("p[name=message]").fadeOut("fast", function() {
        return $(this).fadeIn("fast");
      });
    } else {
      return $(this).show("fast");
    }
  };
  $.fn.createSheet = function() {
    var col, input, row, sheet, tbody, td, tr, x, y, _i, _j;
    sheet = $("#sheet");
    tbody = sheet.find("tbody");
    if (tbody.children().length > 0) {
      $("#sheet_generated").showError();
      sheet.find("input")[0].focus();
    } else {
      x = $(this).find("[name=x]").val();
      y = $(this).find("[name=y]").val();
      input = '<input type="text" autocomplete="off" class="text-center">';
      for (row = _i = 0; _i < y; row = _i += 1) {
        tr = $("<tr>");
        for (col = _j = 0; _j < x; col = _j += 1) {
          td = $("<td class='text-center'>");
          td.append($(input));
          tr.append(td);
        }
        tbody.append(tr);
      }
      sheet.animate({
        height: "toggle",
        opacity: "toggle"
      }, "slow", function() {
        if (!$("#answer").isVisible()) {
          $("#answerInvisibleError").showError();
          $("#answerForm").find("input")[0].focus();
        } else {
          $(this).find("input")[0].focus();
        }
        return sheet.registerKeys();
      });
    }
    return false;
  };
  $.fn.registerKeys = function() {
    $(this).find("input").keypress(function(e) {
      var code, keyEnter;
      keyEnter = 13;
      code = e.keyCode || e.which;
      if (code === keyEnter) {
        $(":input:eq(" + ($(':input').index(this) + 1) + ")").focus();
        return false;
      }
    });
    return $(this);
  };
  $.fn.convert = function() {
    $(this).find("input").each(function() {
      var e, height, input, n, width;
      e = $(this);
      n = Number(e.val());
      width = e.parent().width();
      height = e.parent().height();
      e.parent().width(width);
      e.parent().height(height);
      if (isNaN(n) || n === 0) {
        return e.parent().addClass("cell-block").end().remove();
      } else {
        input = "<input placeholder='" + n + "' type='text' autocomplete='off' class='text-center'>";
        return e.replaceWith(input);
      }
    });
    return $(this);
  };
  $("#answer").submit(function() {
    var error, invalidCell;
    invalidCell = false;
    error = $("#notAllNumberError");
    $(this).find("input").each(function() {
      if (!($(this).val() > 0)) {
        return invalidCell = $(this);
      }
    });
    if (!invalidCell) {
      error.hide("fast");
      $(this).find("button").parent().remove();
      $(this).convert().registerKeys().registerSync();
      $("#sheet").find("input")[0].focus();
    } else {
      invalidCell.focus();
      error.showError();
    }
    return false;
  });
  $("#sheet").submit(function() {
    $(this).find("button").hide("slow").end().convert().registerKeys().registerSync().find("input")[0].focus();
    return false;
  });
  return $.fn.registerSync = function() {
    var elements, target;
    elements = $(this).find("input");
    target = $("#answer,#sheet");
    elements.change(function() {
      var char, n;
      n = $(this).attr("placeholder");
      char = $(this).val();
      target.find("input[placeholder=" + n + "]").sendkeys("{selectall}{del}").sendkeys(char);
      return $(this).focus();
    });
    return $(this);
  };
});
